// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220226071236_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "This is post1 and it has some very interesting content.I have also liked the video and subscibed",
                            Title = "Post1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "This is post2 and it has some very interesting content.I have also liked the video and subscibed",
                            Title = "Post2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is post3 and it has some very interesting content.I have also liked the video and subscibed",
                            Title = "Post3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is post4 and it has some very interesting content.I have also liked the video and subscibed",
                            Title = "Post4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is post5 and it has some very interesting content.I have also liked the video and subscibed",
                            Title = "Post5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "This is post6 and it has some very interesting content.I have also liked the video and subscibed",
                            Title = "Post6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
